First we import numpy

In [2]:
import numpy as np

### Array Creation </br>
---
- ``np.array()``<br>
- ``np.zeros()``<br>
- ``np.ones()``<br>
- ``np.empty()``<br>
- ``np.arange()``<br>
- ``np.linspace()``<br>
- ``dtype``
---

In [ ]:
a = np.array([1,2,3])
b = np.zeros([3,7], dtype=int)
c = np.ones([2,4], dtype=float)
d = np.empty(3, dtype=str)
e = np.arange(5) # Creates an array with a range of elements
f = np.linspace(3, 11, num=9) # Creates an array in range (3,11) with a distribution width of 9
print(f"a = {a}\nb = {b}\nc = {c}\nd = {d}\ne = {e}\nf = {f}")

a = [1 2 3]
b = [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
c = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d = ['' '' '']
e = [0 1 2 3 4]
f = [ 3.  4.  5.  6.  7.  8.  9. 10. 11.]


### Adding, Removing and sorting elements
---
- <span style="color:brown">argsort</span>, which is an indirect sort along a specified axis,<br>
- <span style="color:brown">lexsort</span>, which is an indirect stable sort on multiple keys,<br>
- <span style="color:brown">searchsorted</span>, which will find elements in a sorted array, and<br>
- <span style="color:brown">partition</span>, which is a partial sort.
---

In [ ]:
a = np.array([2,1,3,9,4,5,7])
print(f"Before sort: {a}")
a = np.sort(a)
print(f"After sort: {a}")
b = np.array([13,10,15,16,17,20,11,19])
a = np.concatenate((a,b))
print(f"(a) After concatenation: {a}")
c = np.array([[1,2], [3,4]])
d = np.array([[5,6]])
c = np.concatenate((c,d), axis=0)
print(f"(c) After concatenation: {c}")

Before sort: [2 1 3 9 4 5 7]
After sort: [1 2 3 4 5 7 9]
(a) After concatenation: [ 1  2  3  4  5  7  9 13 10 15 16 17 20 11 19]
(c) After concatenation: [[1 2]
 [3 4]
 [5 6]]


### Array's Shape & Size
+ ndarray.ndim - will tell you the number of axes, or dimensions of the array
+ ndarray.size - will tell you the total number of elements in the array
+ ndarray.shape - will display a tuple of integers that indicate the number
                    of elements stored along each dimension of the array
+ ndarray.reshape

In [13]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(3,2)
print(f"a = {a}")
np.reshape(a, newshape=(2,3), order='F')
# C means to read/write the elements using C-like index order
# F means to read/write the elements using Fortran-like index order
# A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory
# Learn more about them here: https://numpy.org/doc/1.25/dev/internals.html#numpy-internals

a = [[1 2]
 [3 4]
 [5 6]]


array([[1, 5, 4],
       [3, 2, 6]])

### How to add a new-axis to an array?

* np.newaxis - increases dimensions of array by one.
* np.expand_dims - inserts a new axis at a specific position.